### ISSUE TITLE
crash with empty binding table + traffic

### ISSUE THREAD

**Issue by blourdel** [Igalia/snabbswitch#516] opened 2016-10-27 08:28 UTC
A empty binding table is created by the vmx as the binding table file referenced does not exist.
set ietf-softwire:softwire-config binding br jnx-aug-softwire:binding-table-file binding_table.txt

Version : lwaftr v1.1.13

At this stage snabb does not crash and starts with the following log 

cp: /var/db/scripts/commit/binding_table.txt: No such file or directory
md5sum: binding_table.txt: No such file or directory
done
snabbvmx_manager: updated config for snabbvmx!
process_new_config
psid for xe0 is 286
psid for xe1 is 292
--------> snabb xe0:
reading binding file binding_table_empty.txt
Binding table binding_table_empty.txt.s changed. Recompiling ...done.

psid of snabb process for xe0 is 286
forcing binding table reload for xe0 (286)
file snabbvmx-lwaftr-xe0.conf has changed
file snabbvmx-lwaftr-xe0.cfg has changed
sending TERM to snabb process for xe0 (286)
--------> snabb xe1:
reading binding file binding_table_empty.txt
compare files binding_table_empty.txt.s.new binding_table_empty.txt.s
no change detected between binding_table_empty.txt.s.new binding_table_empty.txt.s
psid of snabb process for xe1 is 292
file snabbvmx-lwaftr-xe1.conf has changed
file snabbvmx-lwaftr-xe1.cfg has changed
sending TERM to snabb process for xe1 (292)
cleanup
launch snabbvmx for xe0 on cpu 16 (node 0) after 0 seconds ...
numactl --membind=0 --physcpubind=16 /usr/local/bin/snabb snabbvmx lwaftr --conf snabbvmx-lwaftr-xe0.cfg --id xe0 --pci 0000:08:00.0 --mac 02:3d:dc:07:08:00 --sock %s.socket
launch snabbvmx for xe1 on cpu 17 (node 0) after 1 seconds ...
numactl --membind=0 --physcpubind=17 /usr/local/bin/snabb snabbvmx lwaftr --conf snabbvmx-lwaftr-xe1.cfg --id xe1 --pci 0000:08:00.1 --mac 02:3d:dc:07:08:01 --sock %s.socket
loading compiled binding table from ./binding_table_empty.txt.s.o
compiled binding table ./binding_table_empty.txt.s.o is up to date.
Hairpinning: no
nic_xe0 network ether 02:3d:dc:07:08:00 mtu 9514
IPv6 fragmentation and reassembly: no
IPv4 fragmentation and reassembly: no
lwAFTR service: enabled
nh_fwd6: cache_refresh_interval set to 1 seconds
loading compiled binding table from ./binding_table_empty.txt.s.o
compiled binding table ./binding_table_empty.txt.s.o is up to date.
nh_fwd4: cache_refresh_interval set to 1 seconds
Ingress drop monitor: flush (threshold: 100000 packets; wait: 20 seconds; interval: 1.00 seconds)
Get features 0x18428001
 VIRTIO_F_ANY_LAYOUT VIRTIO_NET_F_MQ VIRTIO_NET_F_CTRL_VQ VIRTIO_NET_F_MRG_RXBUF VIRTIO_RING_F_INDIRECT_DESC VIRTIO_NET_F_CSUM
loading compiled binding table from ./binding_table_empty.txt.s.o
compiled binding table ./binding_table_empty.txt.s.o is up to date.
Hairpinning: no
nic_xe1 network ether 02:3d:dc:07:08:01 mtu 9514
IPv6 fragmentation and reassembly: no
IPv4 fragmentation and reassembly: no
lwAFTR service: enabled
nh_fwd6: cache_refresh_interval set to 1 seconds
vhost_user: Read cached features (0x10028001) from /tmp/vhost_features_xe0.socket
Set features 0x10028001
 VIRTIO_NET_F_CTRL_VQ VIRTIO_NET_F_MRG_RXBUF VIRTIO_RING_F_INDIRECT_DESC VIRTIO_NET_F_CSUM
rxavail = 256 rxused = 256
rxavail = 0 rxused = 0
loading compiled binding table from ./binding_table_empty.txt.s.o
compiled binding table ./binding_table_empty.txt.s.o is up to date.
nh_fwd4: cache_refresh_interval set to 1 seconds
Ingress drop monitor: flush (threshold: 100000 packets; wait: 20 seconds; interval: 1.00 seconds)
Get features 0x18428001
 VIRTIO_F_ANY_LAYOUT VIRTIO_NET_F_MQ VIRTIO_NET_F_CTRL_VQ VIRTIO_NET_F_MRG_RXBUF VIRTIO_RING_F_INDIRECT_DESC VIRTIO_NET_F_CSUM
vhost_user: Read cached features (0x10028001) from /tmp/vhost_features_xe1.socket
Set features 0x10028001
 VIRTIO_NET_F_CTRL_VQ VIRTIO_NET_F_MRG_RXBUF VIRTIO_RING_F_INDIRECT_DESC VIRTIO_NET_F_CSUM
rxavail = 87 rxused = 87
rxavail = 0 rxused = 0
vhost_user: Read cached features (0x10028001) from /tmp/vhost_features_xe0.socket
Set features 0x10028001
 VIRTIO_NET_F_CTRL_VQ VIRTIO_NET_F_MRG_RXBUF VIRTIO_RING_F_INDIRECT_DESC VIRTIO_NET_F_CSUM
rxavail = 0 rxused = 0
vhost_user: Connected and initialized: xe0.socket
rxavail = 0 rxused = 0
vhost_user: Read cached features (0x10028001) from /tmp/vhost_features_xe1.socket
Set features 0x10028001
 VIRTIO_NET_F_CTRL_VQ VIRTIO_NET_F_MRG_RXBUF VIRTIO_RING_F_INDIRECT_DESC VIRTIO_NET_F_CSUM
rxavail = 0 rxused = 0
vhost_user: Connected and initialized: xe1.socket
rxavail = 0 rxused = 0

Then traffic is applied : encapsulation, decapsulation + traffic to the vmx to maintain routing protocol sessions.
This causes a crash: 
core/main.lua:26: packet allocation overflow
stack traceback:
    core/main.lua:137: in function <core/main.lua:135>
    [C]: in function 'error'
    core/main.lua:26: in function 'assert'
    core/packet.lua:161: in function 'preallocate_step'
    core/packet.lua:65: in function 'allocate'
    apps/intel/intel_app.lua:165: in function 'add_receive_buffers'
    apps/intel/intel_app.lua:152: in function 'method'
    core/app.lua:87: in function 'with_restart'
    core/app.lua:319: in function 'thunk'
    core/histogram.lua:98: in function 'breathe'
    core/app.lua:273: in function 'main'
    program/snabbvmx/lwaftr/lwaftr.lua:193: in function 'run'
    program/snabbvmx/snabbvmx.lua:17: in function 'run'
    core/main.lua:56: in function <core/main.lua:43>
    [C]: in function 'xpcall'
    core/main.lua:179: in main chunk
    [C]: at 0x004523e0
    [C]: in function 'pcall'
    core/startup.lua:3: in main chunk
    [C]: in function 'require'
    [string "require "core.startup""]:1: in main chunk

If I try to reproduce by running without vmx, I got crash right away without applying traffic:

root@mx86-24:/root/vmxlwaftr1113/tests/crash2# usr/local/bin/snabb lwaftr run --conf snabbvmx-lwaftr-xe0.conf --on-a-stick 0000:80:00.0
Warning: No NUMA memory affinity.
Pass --cpu to bind to a CPU and its NUMA node.
loading source binding table from ./binding_table_empty.txt.s
core/main.lua:26: failed to open resource /sys/bus/pci/devices/0000:80:00.0/resource0: No such file or directory
stack traceback:
    core/main.lua:137: in function <core/main.lua:135>
    [C]: in function 'error'
    core/main.lua:26: in function 'assert'
    lib/hardware/pci.lua:141: in function 'map_pci_memory_locked'
    apps/intel/intel10g.lua:96: in function 'open'
    apps/intel/intel_app.lua:69: in function 'new'
    core/app.lua:182: in function <core/app.lua:179>
    core/app.lua:222: in function 'apply_config_actions'
    core/app.lua:122: in function 'configure'
    program/lwaftr/run/run.lua:141: in function 'run'
    program/lwaftr/lwaftr.lua:17: in function 'run'
    core/main.lua:56: in function <core/main.lua:43>
    [C]: in function 'xpcall'
    core/main.lua:179: in main chunk
    [C]: at 0x004523e0
    [C]: in function 'pcall'
    core/startup.lua:3: in main chunk
    [C]: in function 'require'
    [string "require "core.startup""]:1: in main chunk

root@mx86-24:/root/vmxlwaftr1113/tests/crash2# usr/local/bin/snabb snabbvmx lwaftr --conf snabbvmx-lwaftr-xe0.cfg --id xe0 --pci 0000:80:00.0 --mac 02:3d:dc:07:08:00
loading compiled binding table from ./binding_table_empty.txt.s.o
compiled binding table ./binding_table_empty.txt.s.o is up to date.
Hairpinning: no
program/snabbvmx/lwaftr/setup.lua:40: bad argument #1 to 'require' (string expected, got nil)
stack traceback:
    core/main.lua:137: in function <core/main.lua:135>
    [C]: in function 'require'
    program/snabbvmx/lwaftr/setup.lua:40: in function 'load_driver'
    program/snabbvmx/lwaftr/setup.lua:84: in function 'load_phy'
    program/snabbvmx/lwaftr/setup.lua:147: in function 'lwaftr_app'
    program/snabbvmx/lwaftr/lwaftr.lua:163: in function 'run'
    program/snabbvmx/snabbvmx.lua:17: in function 'run'
    core/main.lua:56: in function <core/main.lua:43>
    [C]: in function 'xpcall'
    core/main.lua:179: in main chunk
    [C]: at 0x004523e0
    [C]: in function 'pcall'
    core/startup.lua:3: in main chunk
    [C]: in function 'require'
    [string "require "core.startup""]:1: in main chunk

I attach the support info collected:
[support-info-20161026-1204.tgz.zip](https://github.com/Igalia/snabb/files/555285/support-info-20161026-1204.tgz.zip)

**Comment by dpino** [comment] 2016-10-30 23:22
I got a  `packet allocation overflow` in #527. Possibly same cause as described in this bug report. The issue is fixed in #528.

With regard to the error:

``` lua
core/main.lua:26: failed to open resource /sys/bus/pci/devices/
0000:80:00.0/resource0: No such file or directory
```

Usually this error happens when a resource (NIC 0000:80:00.0) is already in use. Make sure there's no other snabb process running on a NIC before run a new snabb process.

**Comment by dpino** [comment] 2016-11-04 18:12
@blourdel #527 has been merged in lwaftr. Could you pull lwaftr branch and try to reproduce the issue again? Thanks

**Comment by dpino** [comment] 2016-12-29 15:20
I triaged the bug in igalia/lwaftr-snabbvmx (equivalent to vmx-docker-lwaftr v1.1.18) and I couldn't reproduce the issue.

**lwaftr --on-a-stick**

```
$ sudo ./snabb lwaftr run --conf snabbvmx-lwaftr-xe0.conf --on-a-stick 83:00.0
Warning: No NUMA memory affinity.
Pass --cpu to bind to a CPU and its NUMA node.
loading compiled binding table from ./binding_table_empty.txt.s.o
compiled binding table ./binding_table_empty.txt.s.o is up to date.
```

**snabbvmx**

```
$ sudo ./snabb snabbvmx lwaftr --conf snabbvmx-lwaftr-xe0.cfg --id xe0 --pci 0000:83:00.0 --mac 02:3d:dc:07:08:00
Warning: config file snabbvmx-lwaftr-xe0.cfg not found
Interface 'xe0' set to passthru mode
Hairpinning: no
nic_xe0 network ether 02:3d:dc:07:08:00 mtu 9514
lwAFTR service: disabled (either empty binding_table or v6 or v4 interface config missing)
Running without VM (no vHostUser sock_path set)
Ingress drop monitor: flush (threshold: 100000 packets; wait: 20 seconds; interval: 1.00 seconds)
```

Closing ticket.

**Closed as completed by dpino** 2016-12-29 15:20 UTC
