### ISSUE TITLE
Augment the lwaftr subcommands tests

### ISSUE THREAD

**Issue by teknico** [Igalia/snabbswitch#775] opened 2017-03-16 15:40 UTC
As [mentioned in a PR](https://github.com/Igalia/snabb/pull/763#discussion_r105152967), we need more subcommands tests. After #412 we have a good start and a nice infrastructure, let's put it to good use. :-)

This issue is meant to record ideas and proposals about specific tests for each subcommand, like the one linked above. Please add anything you consider interesting, then we'll create other issues for each new group of tests we'll implement.

**Comment by teknico** [comment] 2017-03-16 15:44
Comment by @dpino linked above:
> Ideally the monitor test needs more test cases: keyword 'none', set by IPv4 address and setting by PID.

**Comment by kbara** [comment] 2017-03-16 15:45
Ideally, there would be coverage for every option of every command. In practice, that's probably a bit heavyweight for this project, but adding coverage for any command / combination of commands which has had a known regression (at least from now on) strikes me as a good minimum.

**Comment by dpino** [comment] 2018-07-02 08:35
Closing this issue since the monitor tool is barely used and it's likely to be gone in future versions. As for other commands that might be added in the future they must add their own tests.

**Closed as completed by dpino** 2018-07-02 08:35 UTC
